require"user.options"
require"user.keymaps"
require"user.plugins"
require"user.treesitter"
require"user.nvim-tree"
require"user.colors"
require"user.lualine"
require"user.bufferline"
require"user.auto-tag"
require"user.whichkey"
require"user.icons"
require"user.fugitive"
require"user.harpoon"
require"user.indentline"
require"user.toggleterm"
require"user.lsp"
require"user.autopairs"



